### ISSUE TITLE
Battery Icon

### ISSUE THREAD

**Issue by mzavattaro** [billziss-gh/EnergyBar#11]
Would love to have a battery icon that provides the battery status of the device. Would provide more of an incentive to hide the Menu Bar for more screen real estate.

**Comment by billziss-gh** [comment]
I have been thinking about this too. I would probably add it as part of the Clock widget to save space on the Touch Bar.

It would show the time by default, tapping once would have it show the battery, tapping again would have it show the time again.

I have also been thinking about adding a weather display to the clock in the same manner.

**Comment by mzavattaro** [comment]
That could work. Maybe even some sort of graphical interface within the clock interface that changes as the battery indication increases or decreases? Could be as simple as a solid circular line around the time that shrinks and starts green and slowly changes to yellow, orange then red when it's critically low.

**Comment by billziss-gh** [comment]
Also weather display has been added.

![image](https://user-images.githubusercontent.com/15330948/45456640-70e6da00-b6a0-11e8-8dd1-366eac5c6ded.png)

**Comment by billziss-gh** [comment]
EnergyBar version 1.4 is [out](https://github.com/billziss-gh/EnergyBar/releases) and it includes support for battery display.
