### ISSUE TITLE
The clock is one minute back

### ISSUE THREAD

**Issue by alexvan** [billziss-gh/EnergyBar#12]
Version 1.3

**Comment by mzavattaro** [comment]
Also suffering this issue. Version 1.2.

**Comment by billziss-gh** [comment]
I have never seen this and therefore I can only speculate on the reason. How often does this happen for you?

I can see two possibilities:

- Time on macOS is counted as a floating point number, which is inherently imprecise. So for example, the time 12:15:00 may be represented internally as 12:14:59.999...
- The timer is synchronized to start at the minute start (12:15:00), but for some reason it fires just before the real minute change, again resulting in reading the time as 12:14:59.999...

My fix would be to add some time (e.g. 30 seconds) and then throwing away the seconds part, effectively rounding to a minute.

(Or perhaps I have done some other daft thing.)

**Comment by alexvan** [comment]
It's consistently back. Seems being about 30 seconds back.

**Comment by billziss-gh** [comment]
Turns out that the timers were firing correctly and the time was computed correctly. The problem was that for some reason the ClockWidget label would not update some times.

I believe commit 9814ada904f0ac14a6be713068cd3162ec5fe3c8 should fix this. It will be available in version 1.3.

**Comment by billziss-gh** [comment]
[EnergyBar version 1.3](https://github.com/billziss-gh/EnergyBar/releases/tag/v1.3) is out and I believe that it fixes this issue. Let me know if you see otherwise.
