### ISSUE TITLE
Idea: Add a timeout for volume and brightness views

### ISSUE THREAD

**Issue by roderik** [billziss-gh/EnergyBar#13]
When I adjust the volume, I do not have the habit of tapping the cross, so the view stays open. It might be cool if, after x seconds, it closed by itself.

**Comment by billziss-gh** [comment]
@roderik have you tried “press and hold”? Simply press the brightness or volume button for 0.25 seconds and a little indicator will appear. While keeping the button pressed, slightly move your finger left or right and you will see the brightness/volume changed.

**Comment by billziss-gh** [comment]
Understood. I think it is a good idea to add a timer to dismiss the volume/brightness bars after inactivity.

For example, it could be dismissed after 3 seconds of inactivity. Sounds reasonable?

**Comment by roderik** [comment]
Sure!

**Comment by billziss-gh** [comment]
This has been added. I will test it for a while to see if the disappearance of the brightness/volume bars feels surprising. If not it will be available on the next release (which also includes Mojave support).

**Comment by billziss-gh** [comment]
EnergyBar Mojave has been released. Get it [here](
https://github.com/billziss-gh/EnergyBar/releases/latest).
