### ISSUE TITLE
Request : Time left on battery

### ISSUE THREAD

**Issue by stevenvar** [billziss-gh/EnergyBar#22]
Love your app, the only thing I miss from BTT is a way to quickly check how much time is left on battery. Is it possible to add something like this? Thanks

**Comment by billziss-gh** [comment]
This has been added and will be available on the next release (which also includes Mojave support).

**Comment by billziss-gh** [comment]
EnergyBar Mojave has been released. Get it [here](
https://github.com/billziss-gh/EnergyBar/releases/latest).

**Comment by stevenvar** [comment]
Great, thanks a lot
