### ISSUE TITLE
Homebrew Cask

### ISSUE THREAD

**Issue by quulah** [billziss-gh/EnergyBar#26]
I took the liberty of creating a cask in Homebrew for EnergyBar.app.

It's currently a pull request: https://github.com/Homebrew/homebrew-cask/pull/52440

My first cask, so let's see how it goes. :)

Thanks for the useful app!

**Comment by quulah** [comment]
Pull request was merged, and `brew cask install energybar` seems to work as expected, so closing this.

**Comment by billziss-gh** [comment]
Fantastic!

BTW,  I will be adding autoupdate to EnergyBar soon (along with a couple of Mojave fixes). Could the autoupdate mechanism conflict with homebrew’s way of doing things?

**Comment by quulah** [comment]
I don't think that's going to be a problem. At least I have a few autoupdating apps that work fine with Homebrew. Can't really vouch for it though.

Basically the cask just downloads the .zip release and extracts it to /Applications.

**Comment by billziss-gh** [comment]
Understood and thank you again. I will link to your cask from the README in the next update.

**Comment by billziss-gh** [comment]
@quulah I have now added a link to your cask from the README. I linked directly to your formula, because I could not find a web page describing the cask anywhere under https://brew.sh (or elsewhere).

BTW, you may want to update the cask to the latest EnergyBar version 1.5 with Mojave support.
