### ISSUE TITLE
Feature Request: Make Volume Buttons 'Flick-able' like the standard ones

### ISSUE THREAD

**Issue by Kazom** [billziss-gh/EnergyBar#27]
In the control strip on regular Touch Bar you can flick the volume buttons left or right (without having to open the menu, then sliding). For quick interval changes. I would love to see this shortcut also added to the volume buttons in the EnergyBar control strip.

Thanks!

**Comment by billziss-gh** [comment]
@Kazom EnergyBar does not implement "flickable" button, but there is an alternative behavior: If you press and hold the brightness/volume button for 0.25 seconds, you can then move you finger left or right and it will decrease/increase the brightness/volume.

**Comment by billziss-gh** [comment]
@Kazom great! Should we close this issue then?

**Comment by j796160836** [comment]
Hope to see the flickable button in the future.
