### ISSUE TITLE
Escape key does not work

### ISSUE THREAD

**Issue by e96wic** [billziss-gh/EnergyBar#28]
Example: When having spotlight opened, pressing esc does not exit spotlight. Not limited to this scenario.

**Comment by e96wic** [comment]
Solved: You have to grant EnergyBar access to accessibility settings.

**Comment by billziss-gh** [comment]
Yes, this is new in Mojave, which imposes a lot of restrictions on what applications can do in the system. EnergyBar needs access to Accessibility (for <kbd>esc</kbd> to work), Automation (to control the Finder) and Location Services (if using Weather).

**Comment by e96wic** [comment]
@billziss-gh It would be helpful to show a hint or something when pressing escape and the access is not granted :)
