### ISSUE TITLE
feature request : fn to switch f1-f12/normal touchbar function

### ISSUE THREAD

**Issue by wpv** [billziss-gh/EnergyBar#31]
just like original function thx, btw:this app is awesome

**Comment by billziss-gh** [comment]
I am not sure what you are asking for. If you press the Fn key you currently get access to F1, F2, etc. Do you want a different behavior?

**Comment by wpv** [comment]
if i use energybar, all system default behavior will be replace by this app, So I can't use fn to switch it.

**Comment by billziss-gh** [comment]
@wpv the <kbd>fn</kbd> key still works when using EnergyBar. For example, on my Macbook Pro the touch bar reverts to the <kbd>F1</kbd>, <kbd>F2</kbd>, etc. keys when pressing the <kbd>fn</kbd> key.

**Comment by wpv** [comment]
ok thx I got
