### ISSUE TITLE
"Now playing" widget doesn't react to taps

### ISSUE THREAD

**Issue by stepazar** [billziss-gh/EnergyBar#32]
Thanks for the nice Touch Bar solution! 

Everything works except "now playing" widget. It does pause/play, but it doesn't react to taps. Do you know what can be the reason?

**Comment by billziss-gh** [comment]
The "Now Playing" widget cannot be used to play/pause the music. For this purpose use the control widget: 

![](https://github.com/billziss-gh/EnergyBar/raw/master/doc/Control.png)

You can enable taps on the "Now Playing" widget, but all they do is switch the widget to show the "Active App".

**Comment by billziss-gh** [comment]
Sometimes macOS appears to get in a condition where the play/pause buttons do not work even when not using EnergyBar. I am wondering if this one of these cases.

Does rebooting the system not fix the problem?

**Comment by stepazar** [comment]
No, rebooting doesn't help. 

Play/pause actually works very well, but the problem I was trying to report is that this function does't work: "Press and hold the play/pause button to skip backward/forward".

**Comment by billziss-gh** [comment]
Here is how to make this work. Press and hold the play/pause button. Then while holding move your finger to the right of the button to skip forward. Or move your finger to the left of the button to skip backward.

**Comment by stepazar** [comment]
Cool, thanks for the quick response and explanations!

**Comment by billziss-gh** [comment]
No problem. If your issue is resolved perhaps we can close this?
