### ISSUE TITLE
Feature Request : Forward/Back buttons on play controls

### ISSUE THREAD

**Issue by chrissyhroberts** [billziss-gh/EnergyBar#42]
Thanks for this great app. 
It would be brilliant to have optional buttons for moving forward and backwards on media app.

**Comment by billziss-gh** [comment]
You can press and hold the Play button to achieve the same thing. Start pressing the Play button and with your finger still pressing the Touch Bar move it to the left. Lift your finger and this will be a back button press. Do the same gesture for the right direction and it will be a forward button press.

**Comment by chrissyhroberts** [comment]
Thanks, that's brilliant. Very much enhanced experience
