### ISSUE TITLE
[idea] Disable touches while typing 

### ISSUE THREAD

**Issue by developersteve** [billziss-gh/EnergyBar#47]
As someone that sometimes accidentally hits the task bar icons when typing i'm wondering if its possible to have the touchbar icon touches disable while typing.

Did some digging but cant see too much on it either to do it via code or as part of OSX but thought it might be handy. Maybe a transparent overlay over the touchbar screen for 100ms after a keypress or something.

**Comment by billziss-gh** [comment]
That is a pretty neat idea and could be built into EnergyBar.

The only problem is with finding the correct heuristic; your suggestion of ignoring touchbar taps for a short delay after a keypress is a good one.

**Comment by billziss-gh** [comment]
A bit of internet research:

- [`CGEventTapCreate`](https://developer.apple.com/documentation/coregraphics/1454426-cgeventtapcreate): Creates an event tap.
- [`+[NSEvent addGlobalMonitorForEventsMatchingMask:handler:]`](https://developer.apple.com/documentation/appkit/nsevent/1535472-addglobalmonitorforeventsmatchin): Installs an event monitor that receives copies of events posted to other applications.

One of these could perhaps be used to implement the detection part of your heuristic.

**Comment by billziss-gh** [comment]
I ended up implementing this. I need to test it for a few days to make sure that it works and solves the problem, but if it does I will commit the changes soon.

**Comment by developersteve** [comment]
Amazing, was planning to do it as well 👍

**Comment by billziss-gh** [comment]
Thanks! It was a good idea and a nice break from tinkering in the Windows kernel :)

**Comment by billziss-gh** [comment]
Latest release includes this. Closing.
