### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by neumedier** [billziss-gh/EnergyBar#5]
It would be nice to get an HowTo for installation. Many thanks!

**Comment by pheraph** [comment]
1. Download the binary
2. Unzip
3. Drag EnergyBar.app to /Applications
4. Success!?

**Comment by coollittlestoaster** [comment]
Forgive my ignorance, but where is the binary? When I download the zip file from the main page, and unzip the file, I just get the source files and don't see an .app file. Thanks!

**Comment by pheraph** [comment]
The binaries are available on the release page: 

https://github.com/billziss-gh/EnergyBar/releases

**Comment by billziss-gh** [comment]
The binary is in the zip file named `EnergyBar-x.x.xxxxx.zip`.
