### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jacobisaliveandwell** [billziss-gh/EnergyBar#53]
Is there an active fork someone can recommend?

**Comment by billziss-gh** [comment]
This project is not dead. But it is my project and I get to work on it when I want. If you are not happy with this feel free to fork and add the features you want.

**Comment by jacobisaliveandwell** [comment]
@billziss-gh fair, but also why my question is about active forks. I do not develop for macos, and only use this os because I'm forced to for work. To the point of why I ask in the first place; this project doesn't cover the built-in functionality, e.g. keyboard brightness, and the only PR to address this got stale because you haven't replied to the PR since May :-/

**Comment by billziss-gh** [comment]
There is currently no PR that addresses the keyboard brightness.

**Comment by jacobisaliveandwell** [comment]
@billziss-gh see #35, which, unless I am confused about it's purpose, should address the issue by at least surfacing the built-in options.

**Comment by jacobisaliveandwell** [comment]
For anyone that sees this, check out [MTMR](https://github.com/Toxblh/MTMR). It's actively maintained and much more configurable.
