### ISSUE TITLE
Play/pause button not working

### ISSUE THREAD

**Issue by ellie888** [billziss-gh/EnergyBar#55]
The play/pause button isn't working. Have already trying rebooting. Any suggestions? Thanks!

**Comment by billziss-gh** [comment]
Is this with the latest version (1.7?)

**Comment by billziss-gh** [comment]
Please also make sure that the app has the necessary privileges to control your computer. In System Preferences >Privacy, the app needs at a minimum Accessibility and Automation Access.

**Comment by ellie888** [comment]
Thank you! I had to enable screen recording for the app. All good now!
