### ISSUE TITLE
16-inch MacBook support

### ISSUE THREAD

**Issue by dnicolson** [billziss-gh/EnergyBar#57]
Using the 16-inch MacBook I have noticed a few issues:
- The escape button/key is present
- The now playing widget doesn't seem to work with Music
- The Dock contains 5 document icons that are un-tappable
- The image to the left of the Trash button

<img width="1004" alt="Touch Bar Shot 2019-12-17 at 01 41 28" src="https://user-images.githubusercontent.com/2276355/70954774-d3cadc00-206e-11ea-8900-fbe3bad1f9de.png">

EnergyBar v1.7
macOS v10.15.2 (19C57)

**Comment by billziss-gh** [comment]
@dnicolson thanks for the report.

There is currently no 16-inch Macbook Pro support, but I am hoping to look into it.

**Comment by knrz** [comment]
@dnicolson I'm using the 16-inch MacBook and I gotta say man you just have to customize it to your own liking. 

Here's what mine looks like at the moment:
![image](https://user-images.githubusercontent.com/1880797/75043693-78620380-548e-11ea-9d54-3e0706036d24.png)

Use the preferences to customize which apps show up by clicking "Show Folder" and creating aliases from the apps in `/Applications`, and click "Customize" to move things around.
![image](https://user-images.githubusercontent.com/1880797/75043772-90398780-548e-11ea-8f99-1bfa2ecded0d.png)
