### ISSUE TITLE
Clock: Support 24-hour-cycle as alternative to AM/PM

### ISSUE THREAD

**Issue by pheraph** [billziss-gh/EnergyBar#6]
Subject says it all. 🙂

**Comment by billziss-gh** [comment]
This is now added thanks to @pimms. It will be in the next binary release (coming soon).

**Comment by billziss-gh** [comment]
EnergyBar v1.2 is out and includes 24-hour clock support.

https://github.com/billziss-gh/EnergyBar/releases
