### ISSUE TITLE
Brightness does not work when using external screens

### ISSUE THREAD

**Issue by roderik** [billziss-gh/EnergyBar#9]
The brightness widget only works when my macbook is not connected to external screens. Not working meaning changing the slider does nothing to the macbook screen brightness. When running unconnected, it works as expected.

**Comment by billziss-gh** [comment]
We may have to reverse engineer more of Apple's "CoreBrightness" private framework to really fix this problem.

EnergyBar currently uses IOKit ([`Brightness.c`](https://github.com/billziss-gh/EnergyBar/blob/master/src/System/Brightness.c)) to get/set the display brightness and CoreBrightness ([`CBBlueLightClient.h`](https://github.com/billziss-gh/EnergyBar/blob/master/src/System/CBBlueLightClient.h)) for night shift.

**Comment by fifafu** [comment]
I'm the author of another Touch Bar app (BetterTouchTool) and just stumbled upon your nice project.

I'm using the DisplayServices.framework in order to set the brightness, here is a quick example:

```
   CGError		err;
    int			i;
    CGDisplayCount	max;
    CGDirectDisplayID	displayIDs[8];

    err = CGGetOnlineDisplayList(8, displayIDs, &max);
    if(err != kCGErrorSuccess) {
        return;
    }
  
      NSEventModifierFlags flags = [NSEvent modifierFlags];
    for(i = 0; i < max; i++ ) {
        CGDirectDisplayID display = displayIDs[ i ];
        if (( CGDisplayIsBuiltin(display) && !(flags & NSEventModifierFlagControl)) || (!CGDisplayIsBuiltin(display) && (flags & NSEventModifierFlagControl))) {
            DisplayServicesSetBrightnessWithType(display, brightnessValue, 1, 1);
        }
    }
```

**Comment by billziss-gh** [comment]
@fifafu thank you. This is very helpful.

**Comment by billziss-gh** [comment]
[EnergyBar version 1.3](https://github.com/billziss-gh/EnergyBar/releases/tag/v1.3) is out.

I have changed how the brightness control works to always control the "main" display. If this is not desirable, we can also attempt to control the "builtin" display as per @fifafu's suggestion.

Please try this release and let me know if it works for you or what further changes you would want.

**Comment by PowerMike252** [comment]
It works. Good job!

**Comment by billziss-gh** [comment]
Thanks :)

**Comment by roderik** [comment]
Indeed!

**Comment by clemenstyp** [comment]
It did not wokt for me, but I changed it and created a pull request:
https://github.com/billziss-gh/EnergyBar/pull/24
